app:
  env: dev
  metaBase: /
  localStoreKey: nulsSharedNodeRewardsCalculator
  api:
    nulsWorld:
      host: http://localhost
      port: 8081
      base: ''
      resources:
        getNodes: /consensus.json
        getNodeDetail: /consensus/node/__NODE_HASH__.json
        getAddressDetail: /addresses/__ADDRESS__.json
        getBlocks: /blocks.json