app:
  env: dev
  metaBase: /
  localStoreKey: nulsSharedNodeRewardsCalculator
  api:
    nulsWorld:
      host: https://nuls.world
      port: 443
      base: ''
      resources:
        getNodes: /consensus.json